### ISSUE TITLE
html版本docker-compose.yml缩进错误

### ISSUE THREAD

**Issue by ghost** [cnych/kubernetes-learning#15]
https://www.qikqiak.com/k8s-book/docs/8.Docker%20Compose.html#
```
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
```
